apiVersion: apps/v1
kind: Deployment
metadata:
  name: n4
spec:
  selector:
    matchLabels:
      app: n4
  template:
    metadata:
      labels:
        app: n4
    spec:
      containers:
        - image: nginx:1.27
          name: nginx
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      hostPID: true
