apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2
spec:
  selector:
    matchLabels:
      app: n2
  template:
    metadata:
      labels:
        app: n2
    spec:
      containers:
        - image: nginx:1.27
          name: nginx
          volumeMounts:
            - mountPath: /host
              name: host
      volumes:
        - name: host
          hostPath:
            path: /
