---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user5
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: user5
  annotations:
    kubernetes.io/service-account.name: user5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user5
subjects:
  - kind: ServiceAccount
    name: user5
