apiVersion: apps/v1
kind: Deployment
metadata:
  name: n1
spec:
  selector:
    matchLabels:
      app: n1
  template:
    metadata:
      labels:
        app: n1
    spec:
      containers:
        - image: nginx:1.27
          name: nginx
      serviceAccount: sa1
