apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user4
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - watch
      - patch
