---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user4
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: user4
  annotations:
    kubernetes.io/service-account.name: user4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user4
subjects:
  - kind: ServiceAccount
    name: user4
