---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user2
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: user2
  annotations:
    kubernetes.io/service-account.name: user2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user2
  # kind: ClusterRole
  # name: view
subjects:
  - kind: ServiceAccount
    name: user2
